local MAN_HEADER = [[
.TH COGENI-LUA 7 "February 2026" "0.1.0" "cogeni Manual"
.SH NAME
cogeni-lua \- Lua API reference and patterns for cogeni
.SH DESCRIPTION
The \fBcogeni\fR environment provides a suite of modules designed for AST-driven code generation.
.SH GLOBAL VARIABLES
.TP
.B _CURRENT_FILE
Absolute path to the currently executing Lua script.
.TP
.B _FILE_EXTENSION
Extension of the currently executing script (including the dot).
]]

local MAN_FOOTER = [[
.SH EXAMPLES
.SS 1. Basic Generation
.nf
    # <cogeni>
    #   write("hello", "print('hello world')")
    # </cogeni>
    # <generated by="cogeni" id="hello">
    # </cogeni>
.fi
.SS 2. Multi-file Orchestration
.nf
    -- cogeni.lua
    local files = fs.find(".", { type = "f", name = "*.py" })
    for path, _ in pairs(files) do
        async(cogeni.process, path)
    end
.fi
.SH AST TABLE SCHEMA
Every node in the AST is a table:
.TP
.B type
Grammar-defined node name (e.g., "identifier").
.TP
.B fields
Map of named children (e.g., \fBast.fields.name\fR).
.TP
.B children
Ordered list of all sub-nodes.
.TP
.B content
Raw source text (typically only for leaf nodes).
.TP
.B start_pos, end_pos
Coordinate pairs \fB{row, col}\fR.
.SH BEST PRACTICES
.IP \(bu 2
\fBPath Resolution\fR: Always use \fBfs.join(fs.basedir(_CURRENT_FILE), ...)\fR for relative paths.
.IP \(bu 2
\fBConcurrency\fR: Use \fBasync\fR for I/O bound tasks like \fBcogeni.process\fR.
.SH SEE ALSO
.BR cogeni (1)
]]

local function render_details(output, doc)
	if #doc.params > 0 then
		table.insert(output, ".IP\n\\fBParameters:\\fR\n.RS")
		for _, p in ipairs(doc.params) do
			local desc = p.desc or ""
			table.insert(output, "\\fI" .. p.name .. "\\fR (" .. p.type .. "): " .. desc .. "\n.br")
		end
		table.insert(output, ".RE")
	end

	if doc.returns and doc.returns ~= "" then
		table.insert(output, ".IP\n\\fBReturns:\\fR\n.RS\n" .. doc.returns .. "\n.RE")
	end
end

return function(docs_by_module, modules)
	local output = {}
	table.insert(output, MAN_HEADER)

	-- Global Functions
	if docs_by_module["global"] then
		table.insert(output, ".SH GLOBAL FUNCTIONS")
		-- Sort functions
		table.sort(docs_by_module["global"], function(a, b)
			return a.func < b.func
		end)

		for _, doc in ipairs(docs_by_module["global"]) do
			local usage = doc.usage and doc.usage ~= "" and doc.usage or doc.func
			table.insert(output, ".TP\n.B " .. usage)

			if doc.summary and doc.summary ~= "" then
				table.insert(output, doc.summary)
			end
			render_details(output, doc)
		end
	end

	-- Modules
	table.insert(output, ".SH MODULES")

	for _, mod in ipairs(modules) do
		table.insert(output, ".SS " .. mod)
		local funcs = docs_by_module[mod]
		table.sort(funcs, function(a, b)
			return a.func < b.func
		end)

		for _, doc in ipairs(funcs) do
			local usage = doc.usage and doc.usage ~= "" and doc.usage or (mod .. "." .. doc.func)
			table.insert(output, ".TP\n.B " .. usage)

			if doc.summary then
				table.insert(output, doc.summary)
			end
			render_details(output, doc)
		end
	end

	table.insert(output, MAN_FOOTER)

	return table.concat(output, "\n")
end
