from pydantic import BaseModel

class User(BaseModel):
    """A registered user of the system."""
    id: int
    username: str
    email: str

class Product(BaseModel):
    """An item available for purchase."""
    id: int
    name: str
    price: float

class Todo(BaseModel):
    """A task to be completed."""
    id: int
    title: str
    completed: bool

# <cogeni>
#   local ast = cogeni.read_ast(_CURRENT_FILE, "python")
#   local repr_query = [[
#     [.children[] | select(.type == "class_definition") | select(.fields.name.content != "BaseModel")]
#     | map("    def __repr__(self):\n        return f'<" + .fields.name.content + " {self.id}>'")
#     | join("\n\n")
#   ]]
#   write("reprs", jq.query(ast, repr_query))
# </cogeni>

# <generated by="cogeni" id="reprs">
    def __repr__(self):
        return f'<User {self.id}>'

    def __repr__(self):
        return f'<Product {self.id}>'

    def __repr__(self):
        return f'<Todo {self.id}>'
