-- cogeni.lua

-- Static content for the man page
local MAN_HEADER = [[
.TH COGENI-LUA 7 "February 2026" "0.1.0" "cogeni Manual"
.SH NAME
cogeni-lua \- Lua API reference and patterns for cogeni
.SH DESCRIPTION
The \fBcogeni\fR environment provides a suite of modules designed for AST-driven code generation.
.SH GLOBAL VARIABLES
.TP
.B _CURRENT_FILE
Absolute path to the currently executing Lua script.
.TP
.B _FILE_EXTENSION
Extension of the currently executing script (including the dot).
]]

local MAN_FOOTER = [[
.SH EXAMPLES
.SS 1. Basic Generation
.nf
    # <cogeni>
    #   write("hello", "print('hello world')")
    # </cogeni>
    # <generated by="cogeni" id="hello">
    # </cogeni>
.fi
.SS 2. Multi-file Orchestration
.nf
    -- cogeni.lua
    local files = fs.find(".", { type = "f", name = "*.py" })
    for path, _ in pairs(files) do
        async(cogeni.process, path)
    end
.fi
.SH AST TABLE SCHEMA
Every node in the AST is a table:
.TP
.B type
Grammar-defined node name (e.g., "identifier").
.TP
.B fields
Map of named children (e.g., \fBast.fields.name\fR).
.TP
.B children
Ordered list of all sub-nodes.
.TP
.B content
Raw source text (typically only for leaf nodes).
.TP
.B start_pos, end_pos
Coordinate pairs \fB{row, col}\fR.
.SH BEST PRACTICES
.IP \(bu 2
\fBPath Resolution\fR: Always use \fBfs.join(fs.basedir(_CURRENT_FILE), ...)\fR for relative paths.
.IP \(bu 2
\fBConcurrency\fR: Use \fBasync\fR for I/O bound tasks like \fBcogeni.process\fR.
.SH SEE ALSO
.BR cogeni (1)
]]

-- Helper function to parse a doc block
local function parse_doc_block(lines)
	local doc = {
		module = "",
		func = "",
		summary = "",
		usage = "",
		params = {},
		returns = "",
	}

	for _, line in ipairs(lines) do
		-- Strip leading // or spaces
		line = line:gsub("^%s*//%s*", ""):gsub("^%s*", "")

		if line:find("@module") then
			doc.module = line:match("@module%s+(.+)")
		elseif line:find("@function") then
			doc.func = line:match("@function%s+(.+)")
		elseif line:find("@summary") then
			doc.summary = line:match("@summary%s+(.+)")
		elseif line:find("@usage") then
			doc.usage = line:match("@usage%s+(.+)")
		elseif line:find("@param") then
			local p_name, p_type, p_desc = line:match("@param%s+(%S+)%s+(%S+)%s+(.+)")
			if not p_name then
				p_name, p_type = line:match("@param%s+(%S+)%s+(%S+)")
				p_desc = ""
			end
			if not p_name then
				p_name, p_type, p_desc = line:match("@param%s+(%.%.%.)%s+(%S+)%s+(.+)")
			end

			if p_name then
				table.insert(doc.params, { name = p_name, type = p_type, desc = p_desc })
			else
				-- Fallback
				local rest = line:match("@param%s+(.+)")
				table.insert(doc.params, { name = "...", type = "any", desc = rest })
			end
		elseif line:find("@returns") then
			doc.returns = line:match("@returns%s+(.+)")
		end
	end
	return doc
end

-- Collect docs
local docs_by_module = {}

local files = fs.find("src/lua_runtime", { type = "f", name = "*.go" })

for path, _ in pairs(files) do
	local ast = cogeni.read_ast(path, "go")
	local comments = jq.query(ast, '.. | select(.type? == "comment")')
	if type(comments) ~= "table" then
		comments = { comments }
	end

	local in_block = false
	local current_block = {}

	for _, comment in ipairs(comments) do
		local content = comment.content
		if content:find("<lua_api>") then
			in_block = true
			current_block = {}
		elseif content:find("</lua_api>") then
			in_block = false
			local doc = parse_doc_block(current_block)
			if doc.module ~= "" then
				if not docs_by_module[doc.module] then
					docs_by_module[doc.module] = {}
				end
				table.insert(docs_by_module[doc.module], doc)
			end
		elseif in_block then
			table.insert(current_block, content)
		end
	end
end

-- Generate output
local output = {}
table.insert(output, MAN_HEADER)

-- Helper to render details
local function render_details(doc)
	if #doc.params > 0 then
		table.insert(output, ".IP")
		table.insert(output, "\\fBParameters:\\fR")
		table.insert(output, ".RS")
		for _, p in ipairs(doc.params) do
			local desc = p.desc or ""
			table.insert(output, "\\fI" .. p.name .. "\\fR (" .. p.type .. "): " .. desc)
			table.insert(output, ".br")
		end
		table.insert(output, ".RE")
	end

	if doc.returns and doc.returns ~= "" then
		table.insert(output, ".IP")
		table.insert(output, "\\fBReturns:\\fR")
		table.insert(output, ".RS")
		table.insert(output, doc.returns)
		table.insert(output, ".RE")
	end
end

-- Global Functions
if docs_by_module["global"] then
	table.insert(output, ".SH GLOBAL FUNCTIONS")
	-- Sort functions
	table.sort(docs_by_module["global"], function(a, b)
		return a.func < b.func
	end)

	for _, doc in ipairs(docs_by_module["global"]) do
		table.insert(output, ".TP")
		if doc.usage and doc.usage ~= "" then
			table.insert(output, ".B " .. doc.usage)
		else
			table.insert(output, ".B " .. doc.func)
		end

		if doc.summary and doc.summary ~= "" then
			table.insert(output, doc.summary)
		end
		render_details(doc)
	end
end

-- Modules
table.insert(output, ".SH MODULES")

-- Sort module names
local modules = {}
for mod, _ in pairs(docs_by_module) do
	if mod ~= "global" then
		table.insert(modules, mod)
	end
end
table.sort(modules)

for _, mod in ipairs(modules) do
	table.insert(output, ".SS " .. mod)
	local funcs = docs_by_module[mod]
	table.sort(funcs, function(a, b)
		return a.func < b.func
	end)

	for _, doc in ipairs(funcs) do
		table.insert(output, ".TP")
		if doc.usage and doc.usage ~= "" then
			table.insert(output, ".B " .. doc.usage)
		else
			table.insert(output, ".B " .. mod .. "." .. doc.func)
		end

		if doc.summary then
			table.insert(output, doc.summary)
		end
		render_details(doc)
	end
end

table.insert(output, MAN_FOOTER)

local content = table.concat(output, "\n")
cogeni.outfile("lua_man", "docs/man/man7/cogeni-lua.7")
write("lua_man", content)
