from fastapi import FastAPI
import models
from typing import List

app = FastAPI()

# In-memory storage for testing
db = {
    "users": [],
    "products": [],
    "todos": []
}

# <cogeni>
#   local model_path = fs.join(fs.basedir(fs.basedir(_CURRENT_FILE)), "models.py")
#   local ast = cogeni.read_ast(model_path, "python")
#   local query = [[
#     [.children[] | select(.type == "class_definition") | select(.fields.name.content != "BaseModel")]
#     | map(
#         ((.fields.body.children[] | select(.type == "string") | .children[1].content) // "No summary") as $doc
#         | ( .fields.name.content | ascii_downcase ) as $plural
#         | "@app.get('/" + $plural + "s', summary='" + $doc + "', response_model=List[models." + .fields.name.content + "])\ndef get_" + $plural + "s():\n    return db['" + $plural + "s']\n\n" +
#         "@app.post('/" + $plural + "s', summary='Create a new " + .fields.name.content + "')\ndef create_" + $plural + "s(item: models." + .fields.name.content + "):\n    db['" + $plural + "s'].append(item)\n    return item"
#       )
#     | join("\n\n")
#   ]]
#   write("routes", jq.query(ast, query))
# </cogeni>
# <generated by="cogeni" id="routes">
@app.get('/users', summary='A registered user of the system.', response_model=List[models.User])
def get_users():
    return db['users']

@app.post('/users', summary='Create a new User')
def create_users(item: models.User):
    db['users'].append(item)
    return item

@app.get('/products', summary='An item available for purchase.', response_model=List[models.Product])
def get_products():
    return db['products']

@app.post('/products', summary='Create a new Product')
def create_products(item: models.Product):
    db['products'].append(item)
    return item

@app.get('/todos', summary='A task to be completed.', response_model=List[models.Todo])
def get_todos():
    return db['todos']

@app.post('/todos', summary='Create a new Todo')
def create_todos(item: models.Todo):
    db['todos'].append(item)
    return item
# </cogeni>
