#!/usr/bin/env bash
# shellcheck disable=SC2016

describe "Edge Cases and Error Handling"

it "should fail gracefully on malformed lua script" '
    cat > bad_script.lua <<EOF
        this is not lua
EOF
    # Disable set -e for this command as it is expected to fail
    out=$($COGENI_BIN run bad_script.lua 2>&1 || true)
    assert_contains "$out" "failed to execute lua script"
    rm bad_script.lua
'

it "should fail on non-existent file" '
    out=$($COGENI_BIN non_existent.lua 2>&1)
    # The actual error comes from root command if no subcommand is found and it tries to process it as a file
    assert_contains "$out" "failed to read file"
'

it "should handle multiple blocks targeting the same file" "
    cat > multi_target.lua <<EOF
        cogeni.outfile('out1', 'target.txt')
        write('out1', 'content 1')
EOF
    $COGENI_BIN run multi_target.lua
    assert_eq \"\$(cat target.txt)\" \"content 1\"
    rm multi_target.lua target.txt
"

it "should handle multiple blocks targeting the same tag" "
    cat > target_file.txt <<EOF
# <generated by=\"cogeni\" id=\"mytag\">
# </cogeni>
EOF
    cat > multi_tag.lua <<EOF
        cogeni.outtag('mytag', 'target_file.txt', 'mytag')
        write('mytag', 'second')
        cogeni.process('target_file.txt')
EOF
    \$COGENI_BIN run multi_tag.lua
    assert_contains \"\$(cat target_file.txt)\" \"second\"
    rm multi_tag.lua target_file.txt
"
