#!/usr/bin/env bash
# shellcheck disable=SC2016

describe "Cogeni Integration Tests (Full-Stack)"

it "should perform a full clean and then self-heal via generation" '
    # 1. Clean the fullstack project
    $COGENI_BIN clean examples/fullstack/cogeni.lua

    # 2. Verify some key files are emptied of generated content
    # Checking for specific empty generated blocks
    grep -q "id=\"routes\">$" examples/fullstack/backend/routes.py
    grep -q "id=\"types\">$" examples/fullstack/frontend/types.ts

    # Check that the redirected SQL file is empty (just the tag or empty file)
    [[ ! -s examples/fullstack/db/schema.sql ]] || grep -q "^$" examples/fullstack/db/schema.sql

    # 3. Regenerate the code
    $COGENI_BIN run examples/fullstack/cogeni.lua

    # 4. Run the fullstack E2E verification script
    # This script verifies SQLite, FastAPI server, and TS SDK.
    (cd examples/fullstack && ./test.sh)
'

it "should show correct dependency graph for the fullstack project" '
    out=$(cd examples/fullstack && ../../$COGENI_BIN show dependency-graph cogeni.lua 2>&1)
    assert_contains "$out" "models.py"
    assert_contains "$out" "api.ts"
    assert_contains "$out" "types.ts"
'

it "should show diff for pending changes" '
    # Add a new model to trigger a change
    cat >> examples/fullstack/models.py <<EOF
class DiffModel(BaseModel):
    """A model added for testing diffs."""
    id: int
    name: str
EOF

    out=$($COGENI_BIN diff examples/fullstack/backend/routes.py)
    assert_contains "$out" "diffmodels"

    # Revert change by removing the last 4 lines
    head -n -5 examples/fullstack/models.py > examples/fullstack/models.py.tmp && mv examples/fullstack/models.py.tmp examples/fullstack/models.py
'

it "should run cogeni.lua by default in a project directory" '
    mkdir -p tests/data/tmp_proj
    cat > tests/data/tmp_proj/source.txt <<EOF
// <generated by="cogeni" id="msg">
// </cogeni>
EOF
    cat > tests/data/tmp_proj/cogeni.lua <<EOF
        write("msg", "// generated by default")
        cogeni.process("source.txt")
EOF
    (cd tests/data/tmp_proj && ../../../$COGENI_BIN)
    assert_contains "$(cat tests/data/tmp_proj/source.txt)" "// generated by default"
    rm -rf tests/data/tmp_proj
'

it "should support redirection via cogeni.outfile in standalone mode" '
    cat > tests/data/redir_test.py <<EOF
# <cogeni>
#   cogeni.outfile("ext", "redir_target.txt")
#   write("ext", "external content")
# </cogeni>
EOF
    $COGENI_BIN tests/data/redir_test.py

    assert_eq "$(cat tests/data/redir_target.txt)" "external content"
    rm tests/data/redir_test.py tests/data/redir_target.txt
'
