import * as T from "./types";
export class ApiClient {
  constructor(private baseUrl: string) {}
  // <cogeni>
  //   local types_path = fs.join(fs.basedir(_CURRENT_FILE), "types.ts")
  //   local ast = cogeni.read_ast(types_path, "typescript")
  //   local query = [[
  //     [.children[] | select(.type == "export_statement") | .fields.declaration]
  //     | map(
  //         ( .fields.name.content ) as $name |
  //         ( $name | ascii_downcase ) as $plural |
  //         "  async get" + $name + "s(): Promise<T." + $name + "[]> {\n" +
  //         "    const res = await fetch(`${this.baseUrl}/" + $plural + "s`);\n" +
  //         "    return res.json();\n" +
  //         "  }\n\n" +
  //         "  async create" + $name + "(item: T." + $name + "): Promise<T." + $name + "> {\n" +
  //         "    const res = await fetch(`${this.baseUrl}/" + $plural + "s`, {\n" +
  //         "      method: 'POST',\n" +
  //         "      headers: { 'Content-Type': 'application/json' },\n" +
  //         "      body: JSON.stringify(item),\n" +
  //         "    });\n" +
  //         "    return res.json();\n" +
  //         "  }"
  //       )
  //     | join("\n\n")
  //   ]]
  //   write("client", jq.query(ast, query))
  // </cogeni>
  // <generated by="cogeni" id="client">
  async getUsers(): Promise<T.User[]> {
    const res = await fetch(`${this.baseUrl}/users`);
    return res.json();
  }

  async createUser(item: T.User): Promise<T.User> {
    const res = await fetch(`${this.baseUrl}/users`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(item),
    });
    return res.json();
  }

  async getProducts(): Promise<T.Product[]> {
    const res = await fetch(`${this.baseUrl}/products`);
    return res.json();
  }

  async createProduct(item: T.Product): Promise<T.Product> {
    const res = await fetch(`${this.baseUrl}/products`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(item),
    });
    return res.json();
  }

  async getTodos(): Promise<T.Todo[]> {
    const res = await fetch(`${this.baseUrl}/todos`);
    return res.json();
  }

  async createTodo(item: T.Todo): Promise<T.Todo> {
    const res = await fetch(`${this.baseUrl}/todos`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(item),
    });
    return res.json();
  }
  // </cogeni>
}
