// <cogeni>
//   local model_path = fs.join(fs.basedir(fs.basedir(_CURRENT_FILE)), "models.py")
//   local ast = cogeni.read_ast(model_path, "python")
//   local query = [[
//     [.children[] | select(.type == "class_definition") | select(.fields.name.content != "BaseModel")]
//     | map(
//         "export interface " + .fields.name.content + " {\n" +
//         ([.fields.body.children[] | select(.type == "assignment")]
//          | map("  " + .fields.left.content + ": " + (if .fields.type.children[0].content == "int" then "number" elif .fields.type.children[0].content == "float" then "number" elif .fields.type.children[0].content == "bool" then "boolean" else "string" end) + ";")
//          | join("\n")
//         ) + "\n}"
//       )
//     | join("\n\n")
//   ]]
//   write("types", jq.query(ast, query))
// </cogeni>
// <generated by="cogeni" id="types">
export interface User {
  id: number;
  username: string;
  email: string;
}

export interface Product {
  id: number;
  name: string;
  price: number;
}

export interface Todo {
  id: number;
  title: string;
  completed: boolean;
}
// </cogeni>
