// Package luaruntime provides an environment for executing Lua scripts with
// specialized bindings for AST parsing, filesystem access, and data manipulation.
// It uses LuaJIT as the underlying engine and integrates an async scheduler
// to support concurrent operations within Lua scripts.
package luaruntime

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/lucasfabre/codegen/src/astparser"
	"github.com/lucasfabre/codegen/src/config"
	"github.com/lucasfabre/codegen/src/lua_runtime/luajit"
)

// OutputTarget defines the destination for content generated by a 'write()' call.
type OutputTarget struct {
	// Path is the absolute or relative filesystem path of the destination file.
	Path string
	// Tag is the unique identifier of the <generated> block within the destination file.
	// If empty, the entire destination file will be replaced.
	Tag string
}

// LuaRuntime is a wrapper around the Lua state that provides cogeni-specific modules.
type LuaRuntime struct {
	// L is the underlying LuaJIT state.
	L      *luajit.State
	cfg    *config.Config
	parser *astparser.Parser
	// Output stores the results from 'write(id, content)' calls. Key is the block ID.
	Output map[string]string
	// OutputTargets maps block IDs to their destination target files and tags.
	OutputTargets map[string]OutputTarget
	// ProcessFunc is a hook called when cogeni.process() is invoked in Lua.
	// Parameters: (target_path, requestor_path).
	ProcessFunc func(string, string) error
	// WaitFunc is a hook called to ensure inter-file dependency ordering.
	// Parameters: (target_path, requestor_path).
	WaitFunc func(string, string) error
	// ReadFunc is a hook to retrieve buffered content for a file path.
	// Parameters: (path). Returns (content, found).
	ReadFunc func(string) (string, bool)

	Scheduler *Scheduler
}

// New initializes a LuaRuntime.
func New(cfg *config.Config) (*LuaRuntime, error) {
	parser, err := astparser.New(cfg.Grammar.Location)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize parser: %w", err)
	}

	rt := &LuaRuntime{
		L:             luajit.NewState(),
		cfg:           cfg,
		parser:        parser,
		Output:        make(map[string]string),
		OutputTargets: make(map[string]OutputTarget),
		Scheduler:     NewScheduler(),
	}

	if rt.L == nil {
		return nil, fmt.Errorf("failed to create Lua state")
	}

	rt.L.OpenLibs()

	// Register modules
	rt.registerCogeniModule()
	rt.registerJSONModule()
	rt.registerYAMLModule()
	rt.registerTOMLModule()
	rt.registerXMLModule()
	rt.registerJQModule()
	rt.registerFSModule()

	// Register globals
	rt.L.PushGoFunction(func(L *luajit.State) int {
		sec := L.CheckNumber(1)
		return rt.Scheduler.AsyncRun(L, func() []interface{} {
			time.Sleep(time.Duration(sec * float64(time.Second)))
			return nil
		})
	})
	// <lua_api>
	// @module global
	// @function sleep
	// @summary Pauses execution for a given number of seconds.
	// @usage sleep(seconds)
	// @param seconds number The number of seconds to sleep.
	// </lua_api>
	rt.L.SetGlobal("sleep")

	rt.L.PushGoFunction(func(L *luajit.State) int {
		id := L.CheckString(1)
		content := ""

		if L.IsTable(2) {
			length := L.ObjLen(2)
			var sb strings.Builder
			for i := 1; i <= length; i++ {
				L.RawGetInt(2, i)
				if L.IsString(-1) {
					sb.WriteString(L.ToString(-1))
					if i < length {
						sb.WriteString("\n")
					}
				}
				L.Pop(1)
			}
			content = sb.String()
		} else {
			content = L.CheckString(2)
		}

		rt.Output[id] = content
		return 0
	})
	// <lua_api>
	// @module global
	// @function write
	// @summary Buffers generated content for a specific target identifier.
	// @usage write(id, content)
	// @param id string The target identifier (tag or file ID).
	// @param content string|table The content to write. If table, joins elements with newlines.
	// </lua_api>
	rt.L.SetGlobal("write")

	// Implement async
	rt.L.PushGoFunction(func(L *luajit.State) int {
		if !L.IsFunction(1) {
			L.PushString("expected function")
			L.Error()
			return 0
		}

		T := L.NewThread()
		// Move function and args to T
		nArgs := L.GetTop() - 1

		L.PushValue(1) // fn
		L.XMove(T, 1)

		for i := 2; i <= L.GetTop(); i++ {
			L.PushValue(i)
			L.XMove(T, 1)
		}

		rt.Scheduler.Register(T)

		status, err := T.Resume(nArgs)
		if err != nil {
			rt.Scheduler.Unregister(T)
			L.PushString(err.Error())
			L.Error()
		}

		if status == luajit.OK {
			rt.Scheduler.NotifyFinished(T)
			rt.Scheduler.Unregister(T)
		}

		return 1
	})
	// <lua_api>
	// @module global
	// @function async
	// @summary Spawns an asynchronous task.
	// @usage async(fn, ...)
	// @param fn function The function to run asynchronously.
	// @param ... any Arguments to pass to the function.
	// @returns thread The coroutine thread handle.
	// </lua_api>
	rt.L.SetGlobal("async")

	// Implement internal await for threads
	rt.L.PushGoFunction(func(L *luajit.State) int {
		if L.IsFunction(1) {
			L.Call(L.GetTop()-1, luajit.MULTRET)
			return L.GetTop()
		}

		target := L.ToThread(1)
		if target == nil {
			L.PushValue(1)
			return 1
		}

		done := rt.Scheduler.Await(L, target)
		if done {
			// Target is already finished. Move results from target stack to current stack.
			nResults := target.GetTop()
			if nResults > 0 {
				target.XMove(L, nResults)
				return nResults
			}
			return 0
		}

		return L.Yield(0)
	})
	rt.L.SetGlobal("_await_thread")

	// <lua_api>
	// @module global
	// @function await
	// @summary Waits for an asynchronous task or thread to complete and returns its results.
	// @usage result = await(target, ...)
	// @param target function|thread The task or thread to wait for.
	// @param ... any Arguments if target is a function.
	// @returns any The results from the completed task.
	// </lua_api>

	// Define await in Lua to handle function calls
	err = rt.L.DoString(`
		function await(target, ...)
			if type(target) == "function" then
				return target(...)
			end
			return _await_thread(target)
		end
	`)
	if err != nil {
		return nil, fmt.Errorf("failed to define await: %w", err)
	}

	for name, src := range cfg.Grammar.Sources {
		rt.parser.RegisterGrammar(name, src.URL, astparser.GrammarOptions{
			Branch:   src.Branch,
			BuildCmd: src.BuildCmd,
			Artifact: src.Artifact,
		})
	}

	return rt, nil
}

// Close releases the resources associated with the Lua state.
func (rt *LuaRuntime) Close() {
	rt.L.Close()
}

// Reset clears the runtime state for reuse in a pool.
func (rt *LuaRuntime) Reset() {
	rt.Output = make(map[string]string)
	rt.OutputTargets = make(map[string]OutputTarget)
	rt.Scheduler = NewScheduler()

	rt.L.PushNil()
	rt.L.SetGlobal("_CURRENT_FILE")
	rt.L.PushNil()
	rt.L.SetGlobal("_FILE_EXTENSION")
}

// Schedule triggers the execution of pending async tasks.
func (rt *LuaRuntime) Schedule() {
	// No-op
}

// ExecuteFile loads and runs a Lua script from the filesystem.
func (rt *LuaRuntime) ExecuteFile(filePath string) error {
	absPath, _ := filepath.Abs(filePath)

	rt.L.PushString(absPath)
	rt.L.SetGlobal("_CURRENT_FILE")

	rt.L.PushString(filepath.Ext(filePath))
	rt.L.SetGlobal("_FILE_EXTENSION")

	T := rt.L.NewThread()
	ref := rt.L.Ref(luajit.LUA_REGISTRYINDEX)
	defer rt.L.Unref(luajit.LUA_REGISTRYINDEX, ref)

	if err := T.LoadFile(filePath); err != nil {
		return fmt.Errorf("failed to execute lua script '%s': %w", filePath, err)
	}

	if err := rt.Scheduler.Start(T); err != nil {
		return fmt.Errorf("failed to execute lua script '%s': %w", filePath, err)
	}
	return nil
}

// DoString executes a raw string of Lua code.
func (rt *LuaRuntime) DoString(code string) error {
	T := rt.L.NewThread()
	ref := rt.L.Ref(luajit.LUA_REGISTRYINDEX)
	defer rt.L.Unref(luajit.LUA_REGISTRYINDEX, ref)

	if err := T.LoadString(code); err != nil {
		return err
	}

	// Run via Scheduler
	return rt.Scheduler.Start(T)
}

// REPL starts an interactive Lua session with all cogeni modules available.
func (rt *LuaRuntime) REPL() error {
	scanner := bufio.NewScanner(os.Stdin)
	fmt.Println("cogeni interactive REPL")
	fmt.Println("Type 'exit' or press Ctrl+D to quit.")
	for {
		fmt.Print("> ")
		if !scanner.Scan() {
			break
		}
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "exit" || trimmed == "quit" {
			break
		}
		if trimmed == "" {
			continue
		}
		if err := rt.L.DoString(line); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		}
		rt.L.Flush()
	}
	return scanner.Err()
}

// registerCogeniModule exposes the 'cogeni' table to Lua.
func (rt *LuaRuntime) registerCogeniModule() {
	rt.L.CreateTable(0, 6)
	rt.L.PushGoFunction(rt.cogeniReadAST)
	rt.L.SetField(-2, "read_ast")
	rt.L.PushGoFunction(rt.cogeniRegisterGrammar)
	rt.L.SetField(-2, "register_grammar")
	rt.L.PushGoFunction(rt.cogeniGetGrammar)
	rt.L.SetField(-2, "get_grammar")
	rt.L.PushGoFunction(rt.cogeniProcess)
	rt.L.SetField(-2, "process")
	rt.L.PushGoFunction(func(L *luajit.State) int {
		id := L.CheckString(1)
		path := L.CheckString(2)
		rt.OutputTargets[id] = OutputTarget{Path: path, Tag: ""}
		return 0
	})
	rt.L.SetField(-2, "outfile")
	rt.L.PushGoFunction(func(L *luajit.State) int {
		id := L.CheckString(1)
		path := L.CheckString(2)
		tag := L.CheckString(3)
		rt.OutputTargets[id] = OutputTarget{Path: path, Tag: tag}
		return 0
	})
	rt.L.SetField(-2, "outtag")
	rt.L.SetGlobal("cogeni")
}

// registerFSModule exposes the 'fs' table to Lua for filesystem utilities.
func (rt *LuaRuntime) registerFSModule() {
	rt.L.CreateTable(0, 4)
	rt.L.PushGoFunction(rt.fsFind)
	rt.L.SetField(-2, "find")
	rt.L.PushGoFunction(rt.fsBaseDir)
	rt.L.SetField(-2, "basedir")
	rt.L.PushGoFunction(rt.fsBaseName)
	rt.L.SetField(-2, "basename")
	rt.L.PushGoFunction(rt.fsPathJoin)
	rt.L.SetField(-2, "join")
	rt.L.SetGlobal("fs")
}

// registerJSONModule exposes the 'json' table to Lua for JSON serialization.
func (rt *LuaRuntime) registerJSONModule() {
	rt.L.CreateTable(0, 2)
	rt.L.PushGoFunction(rt.jsonEncode)
	rt.L.SetField(-2, "encode")
	rt.L.PushGoFunction(rt.jsonDecode)
	rt.L.SetField(-2, "decode")
	rt.L.SetGlobal("json")
}

// registerJQModule exposes the 'jq' table to Lua for JQ querying of AST nodes.
func (rt *LuaRuntime) registerJQModule() {
	rt.L.CreateTable(0, 1)
	rt.L.PushGoFunction(rt.jqQuery)
	rt.L.SetField(-2, "query")
	rt.L.SetGlobal("jq")
}

// registerYAMLModule exposes the 'yaml' table to Lua for YAML serialization.
func (rt *LuaRuntime) registerYAMLModule() {
	rt.L.CreateTable(0, 2)
	rt.L.PushGoFunction(rt.yamlEncode)
	rt.L.SetField(-2, "encode")
	rt.L.PushGoFunction(rt.yamlDecode)
	rt.L.SetField(-2, "decode")
	rt.L.SetGlobal("yaml")
}

// registerTOMLModule exposes the 'toml' table to Lua for TOML serialization.
func (rt *LuaRuntime) registerTOMLModule() {
	rt.L.CreateTable(0, 2)
	rt.L.PushGoFunction(rt.tomlEncode)
	rt.L.SetField(-2, "encode")
	rt.L.PushGoFunction(rt.tomlDecode)
	rt.L.SetField(-2, "decode")
	rt.L.SetGlobal("toml")
}

// registerXMLModule exposes the 'xml' table to Lua for XML serialization.
func (rt *LuaRuntime) registerXMLModule() {
	rt.L.CreateTable(0, 2)
	rt.L.PushGoFunction(rt.xmlEncode)
	rt.L.SetField(-2, "encode")
	rt.L.PushGoFunction(rt.xmlDecode)
	rt.L.SetField(-2, "decode")
	rt.L.SetGlobal("xml")
}
