// Package luaruntime provides an environment for executing Lua scripts with
// specialized bindings for AST parsing, filesystem access, and data manipulation.
// It uses gopher-lua as the underlying engine and integrates an async scheduler
// to support concurrent operations within Lua scripts.
package luaruntime

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	async "github.com/CuberL/glua-async"
	"github.com/lucasfabre/codegen/src/astparser"
	"github.com/lucasfabre/codegen/src/config"
	lua "github.com/yuin/gopher-lua"
)

// OutputTarget defines the destination for content generated by a 'write()' call.
type OutputTarget struct {
	// Path is the absolute or relative filesystem path of the destination file.
	Path string
	// Tag is the unique identifier of the <generated> block within the destination file.
	// If empty, the entire destination file will be replaced.
	Tag string
}

// LuaRuntime is a wrapper around the Lua state that provides cogeni-specific modules.
type LuaRuntime struct {
	// L is the underlying gopher-lua state.
	L      *lua.LState
	cfg    *config.Config
	parser *astparser.Parser
	// Output stores the results from 'write(id, content)' calls. Key is the block ID.
	Output map[string]string
	// OutputTargets maps block IDs to their destination target files and tags.
	OutputTargets map[string]OutputTarget
	// ProcessFunc is a hook called when cogeni.process() is invoked in Lua.
	// Parameters: (target_path, requestor_path).
	ProcessFunc func(string, string) error
	// WaitFunc is a hook called to ensure inter-file dependency ordering.
	// Parameters: (target_path, requestor_path).
	WaitFunc func(string, string) error
	// ReadFunc is a hook to retrieve buffered content for a file path.
	// Parameters: (path). Returns (content, found).
	ReadFunc func(string) (string, bool)
}

// New initializes a LuaRuntime.
//
// <lua_api>
// @module global
// @function write
// @summary Buffers text for a specific output block.
// @usage write(id, content)
// @param id string The block ID.
// @param content string The content to write.
// </lua_api>
//
// <lua_api>
// @module global
// @function async
// @summary Starts a new asynchronous task.
// @usage async(fn, ...)
// @param fn function The function to run asynchronously.
// @param ... any Arguments to pass to the function.
// @returns userdata A job handle.
// </lua_api>
//
// <lua_api>
// @module global
// @function await
// @summary Pauses until a job completes.
// @usage await(job)
// @param job userdata The job handle to wait for.
// @returns ... any The results of the async function.
// </lua_api>
//
// <lua_api>
// @module global
// @function sleep
// @summary Pauses execution for a duration.
// @usage sleep(seconds)
// @param seconds number The number of seconds to sleep.
// </lua_api>
func New(cfg *config.Config) (*LuaRuntime, error) {
	parser, err := astparser.New(cfg.Grammar.Location)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize parser: %w", err)
	}

	rt := &LuaRuntime{
		L:             lua.NewState(),
		cfg:           cfg,
		parser:        parser,
		Output:        make(map[string]string),
		OutputTargets: make(map[string]OutputTarget),
	}

	rt.L.OpenLibs()
	rt.registerCogeniModule()
	rt.registerJSONModule()
	rt.registerYAMLModule()
	rt.registerTOMLModule()
	rt.registerXMLModule()
	rt.registerJQModule()
	rt.registerFSModule()

	async.Init(rt.L)

	rt.L.SetGlobal("sleep", rt.L.NewFunction(func(L *lua.LState) int {
		sec := L.CheckNumber(1)
		async.AsyncRun(func() []lua.LValue {
			time.Sleep(time.Duration(float64(sec) * float64(time.Second)))
			return nil
		}, L)
		return 0
	}))

	for name, src := range cfg.Grammar.Sources {
		rt.parser.RegisterGrammar(name, src.URL, astparser.GrammarOptions{
			Branch:   src.Branch,
			BuildCmd: src.BuildCmd,
			Artifact: src.Artifact,
		})
	}

	rt.L.SetGlobal("write", rt.L.NewFunction(func(L *lua.LState) int {
		id := L.CheckString(1)
		content := L.CheckString(2)
		rt.Output[id] = content
		return 0
	}))

	return rt, nil
}

// Close releases the resources associated with the Lua state.
func (rt *LuaRuntime) Close() {
	rt.L.Close()
}

// Reset clears the runtime state for reuse in a pool.
func (rt *LuaRuntime) Reset() {
	rt.Output = make(map[string]string)
	rt.OutputTargets = make(map[string]OutputTarget)

	rt.L.SetGlobal("_CURRENT_FILE", lua.LNil)
	rt.L.SetGlobal("_FILE_EXTENSION", lua.LNil)
}

// Schedule triggers the execution of pending async tasks.
func (rt *LuaRuntime) Schedule() {
	async.Schedule(rt.L)
}

// ExecuteFile loads and runs a Lua script from the filesystem.
func (rt *LuaRuntime) ExecuteFile(filePath string) error {
	absPath, _ := filepath.Abs(filePath)
	rt.L.SetGlobal("_CURRENT_FILE", lua.LString(absPath))
	rt.L.SetGlobal("_FILE_EXTENSION", lua.LString(filepath.Ext(filePath)))

	if err := rt.L.DoFile(filePath); err != nil {
		return fmt.Errorf("failed to execute lua script '%s': %w", filePath, err)
	}
	return nil
}

// DoString executes a raw string of Lua code.
func (rt *LuaRuntime) DoString(code string) error {
	if err := rt.L.DoString(code); err != nil {
		return err
	}
	return nil
}

// REPL starts an interactive Lua session with all cogeni modules available.
func (rt *LuaRuntime) REPL() error {
	scanner := bufio.NewScanner(os.Stdin)
	fmt.Println("cogeni interactive REPL")
	fmt.Println("Type 'exit' or press Ctrl+D to quit.")
	for {
		fmt.Print("> ")
		if !scanner.Scan() {
			break
		}
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "exit" || trimmed == "quit" {
			break
		}
		if trimmed == "" {
			continue
		}
		if err := rt.L.DoString(line); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		}
	}
	return scanner.Err()
}

// registerCogeniModule exposes the 'cogeni' table to Lua.
//
// <lua_api>
// @module cogeni
// @function outfile
// @summary Redirects write(id) to a file.
// @usage cogeni.outfile(id, path)
// @param id string The block ID.
// @param path string The file path to overwrite.
// </lua_api>
//
// <lua_api>
// @module cogeni
// @function outtag
// @summary Redirects write(id) to a specific tag in a file.
// @usage cogeni.outtag(id, path, tag)
// @param id string The block ID.
// @param path string The file path.
// @param tag string The tag in the file.
// </lua_api>
func (rt *LuaRuntime) registerCogeniModule() {
	cogeniTable := rt.L.CreateTable(0, 6)
	rt.L.SetField(cogeniTable, "read_ast", rt.L.NewFunction(rt.cogeniReadAST))
	rt.L.SetField(cogeniTable, "register_grammar", rt.L.NewFunction(rt.cogeniRegisterGrammar))
	rt.L.SetField(cogeniTable, "get_grammar", rt.L.NewFunction(rt.cogeniGetGrammar))
	rt.L.SetField(cogeniTable, "process", rt.L.NewFunction(rt.cogeniProcess))

	rt.L.SetField(cogeniTable, "outfile", rt.L.NewFunction(func(L *lua.LState) int {
		id := L.CheckString(1)
		path := L.CheckString(2)
		rt.OutputTargets[id] = OutputTarget{Path: path, Tag: ""}
		return 0
	}))

	rt.L.SetField(cogeniTable, "outtag", rt.L.NewFunction(func(L *lua.LState) int {
		id := L.CheckString(1)
		path := L.CheckString(2)
		tag := L.CheckString(3)
		rt.OutputTargets[id] = OutputTarget{Path: path, Tag: tag}
		return 0
	}))
	rt.L.SetGlobal("cogeni", cogeniTable)
}

// registerFSModule exposes the 'fs' table to Lua for filesystem utilities.
func (rt *LuaRuntime) registerFSModule() {
	fsTable := rt.L.CreateTable(0, 4)
	rt.L.SetField(fsTable, "find", rt.L.NewFunction(rt.fsFind))
	rt.L.SetField(fsTable, "basedir", rt.L.NewFunction(rt.fsBaseDir))
	rt.L.SetField(fsTable, "basename", rt.L.NewFunction(rt.fsBaseName))
	rt.L.SetField(fsTable, "join", rt.L.NewFunction(rt.fsPathJoin))
	rt.L.SetGlobal("fs", fsTable)
}

// registerJSONModule exposes the 'json' table to Lua for JSON serialization.
func (rt *LuaRuntime) registerJSONModule() {
	jsonTable := rt.L.CreateTable(0, 2)
	rt.L.SetField(jsonTable, "encode", rt.L.NewFunction(rt.jsonEncode))
	rt.L.SetField(jsonTable, "decode", rt.L.NewFunction(rt.jsonDecode))
	rt.L.SetGlobal("json", jsonTable)
}

// registerJQModule exposes the 'jq' table to Lua for JQ querying of AST nodes.
func (rt *LuaRuntime) registerJQModule() {
	jqTable := rt.L.CreateTable(0, 1)
	rt.L.SetField(jqTable, "query", rt.L.NewFunction(rt.jqQuery))
	rt.L.SetGlobal("jq", jqTable)
}

// registerYAMLModule exposes the 'yaml' table to Lua for YAML serialization.
func (rt *LuaRuntime) registerYAMLModule() {
	yamlTable := rt.L.CreateTable(0, 2)
	rt.L.SetField(yamlTable, "encode", rt.L.NewFunction(rt.yamlEncode))
	rt.L.SetField(yamlTable, "decode", rt.L.NewFunction(rt.yamlDecode))
	rt.L.SetGlobal("yaml", yamlTable)
}

// registerTOMLModule exposes the 'toml' table to Lua for TOML serialization.
func (rt *LuaRuntime) registerTOMLModule() {
	tomlTable := rt.L.CreateTable(0, 2)
	rt.L.SetField(tomlTable, "encode", rt.L.NewFunction(rt.tomlEncode))
	rt.L.SetField(tomlTable, "decode", rt.L.NewFunction(rt.tomlDecode))
	rt.L.SetGlobal("toml", tomlTable)
}

// registerXMLModule exposes the 'xml' table to Lua for XML serialization.
func (rt *LuaRuntime) registerXMLModule() {
	xmlTable := rt.L.CreateTable(0, 2)
	rt.L.SetField(xmlTable, "encode", rt.L.NewFunction(rt.xmlEncode))
	rt.L.SetField(xmlTable, "decode", rt.L.NewFunction(rt.xmlDecode))
	rt.L.SetGlobal("xml", xmlTable)
}
