-- examples/performance/generate.lua
-- This script generates a stress test environment for cogeni.
-- It creates Python files with inter-dependencies and accompanying configuration files.

local NUM_FILES = 1000
-- Directory for mkdir (relative to CWD of execution, which is repo root)
local MKDIR_DIR = "examples/performance/src"
-- Directory for cogeni.outfile (relative to this script)
local OUT_DIR = "src"

-- Helper to ensure directory exists
os.execute("mkdir -p " .. MKDIR_DIR)

print(string.format("Generating %d files in %s...", NUM_FILES, MKDIR_DIR))

local start_time = os.time()

for i = 1, NUM_FILES do
	local file_id = "file_" .. i
	local filename = file_id .. ".py"
	local filepath = fs.join(OUT_DIR, filename)
	local config_id = "config_" .. i
	local config_path = fs.join(OUT_DIR, config_id .. ".json")

	-- Register output targets
	cogeni.outfile(file_id, filepath)
	cogeni.outfile(config_id, config_path)

	-- 1. Generate Python File
	local py_content = {}
	table.insert(py_content, "import random")
	table.insert(py_content, "import time")
	table.insert(py_content, "import json")

	-- Random imports to create a dependency graph
	local num_imports = math.random(1, 3)
	local imported = {}
	for j = 1, num_imports do
		local other_idx = math.random(1, NUM_FILES)
		if other_idx ~= i and not imported[other_idx] then
			table.insert(py_content, string.format("from %s import Class_%d", "file_" .. other_idx, other_idx))
			imported[other_idx] = true
		end
	end

	table.insert(py_content, "")
	table.insert(py_content, string.format("class Class_%d:", i))
	table.insert(py_content, "    def __init__(self):")
	table.insert(py_content, string.format("        self.value = %d", i))
	table.insert(py_content, "")
	table.insert(py_content, "    def compute(self):")
	table.insert(py_content, "        # Simulate some work")
	table.insert(py_content, "        time.sleep(0.0001)")
	table.insert(py_content, "        return self.value * 2")
	table.insert(py_content, "")

	-- Embedded cogeni block for recursive processing
	-- This block will be executed when cogeni processes the generated file
	table.insert(py_content, "# <cogeni>")
	table.insert(py_content, "#   -- Read own AST to stress tree-sitter")
	table.insert(py_content, "#   local ast = cogeni.read_ast(_CURRENT_FILE, 'python')")
	table.insert(py_content, "#   -- JQ query to find function definitions (using gojq syntax)")
	table.insert(py_content, "#   local functions = jq.query(ast, '.. | select(.type? == \"function_definition\")')")
	table.insert(py_content, "#   if type(functions) ~= 'table' then functions = {functions} end")
	table.insert(py_content, "#   local count = #functions")
	table.insert(py_content, "# ")
	table.insert(py_content, "#   -- Read accompanying JSON config")
	table.insert(py_content, "#   -- Convert file_N.py -> config_N.json")
	table.insert(py_content, "#   local dir = fs.basedir(_CURRENT_FILE)")
	table.insert(py_content, "#   local name = fs.basename(_CURRENT_FILE)")
	table.insert(py_content, "#   local config_name = name:gsub('file_', 'config_'):gsub('%.py$', '.json')")
	table.insert(py_content, "#   local json_path = fs.join(dir, config_name)")
	table.insert(py_content, "#   local f = io.open(json_path, 'r')")
	table.insert(py_content, "#   if f then")
	table.insert(py_content, "#     local content = f:read('*a')")
	table.insert(py_content, "#     f:close()")
	table.insert(py_content, "#     local data = json.decode(content)")
	table.insert(py_content, "#     -- Write output based on analysis")
	table.insert(
		py_content,
		string.format(
			"#     write('stats_%d', string.format('Analysis: found %%d functions, config id: %%d', count, data.id))",
			i
		)
	)
	table.insert(py_content, "#   else")
	table.insert(py_content, "#     print('Warning: could not find config at ' .. json_path)")
	table.insert(py_content, "#   end")
	table.insert(py_content, "# </cogeni>")

	-- Target for the generated content
	-- Note: cogeni requires double quotes for attributes in <generated> tags
	table.insert(py_content, string.format('# <generated by="cogeni" id="stats_%d">', i))
	table.insert(py_content, "# </generated>")

	write(file_id, table.concat(py_content, "\n"))

	-- 2. Generate JSON Config File
	local config_data = {
		id = i,
		name = config_id,
		random_val = math.random(),
		metadata = {
			created_at = os.time(),
			type = "stress_test",
		},
	}
	write(config_id, json.encode(config_data))

	if i % 100 == 0 then
		print(string.format("Generated %d files...", i))
	end
end

local duration = os.time() - start_time
print(string.format("Done. Generated %d files (and %d configs) in %d seconds.", NUM_FILES, NUM_FILES, duration))
