package processor

import (
	"testing"
)

func TestExtractCogeniBlocks(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name: "basic block",
			input: `
-- <cogeni>
print("hello")
-- </cogeni>
`,
			expected: "print(\"hello\")\n",
		},
		{
			name: "indented block",
			input: `
    // <cogeni>
    print("indented")
    // </cogeni>
`,
			expected: "print(\"indented\")\n",
		},
		{
			name: "block with different comment style",
			input: `
# <cogeni>
print("python style")
# </cogeni>
`,
			expected: "print(\"python style\")\n",
		},
		{
			name: "multiple blocks",
			input: `
// <cogeni>
print("first")
// </cogeni>
some other code
// <cogeni>
print("second")
// </cogeni>
`,
			expected: "print(\"first\")\nprint(\"second\")\n",
		},
		{
			name: "mixed indentation",
			input: `
  // <cogeni>
  print("line 1")
    print("line 2")
  // </cogeni>
`,
			expected: "print(\"line 1\")\n  print(\"line 2\")\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ExtractCogeniBlocks(tt.input)
			if got != tt.expected {
				t.Errorf("ExtractCogeniBlocks() = %q, want %q", got, tt.expected)
			}
		})
	}
}

func TestReplaceGeneratedBlocks(t *testing.T) {
	outputs := map[string]string{
		"test1": "generated content 1",
		"test2": "generated content 2",
	}

	tests := []struct {
		name     string
		input    string
		outputs  map[string]string
		cleanAll bool
		expected string
	}{
		{
			name: "basic replacement",
			input: `
// <generated by="cogeni" id="test1">
old content
// </cogeni>
`,
			outputs:  outputs,
			cleanAll: false,
			expected: `
// <generated by="cogeni" id="test1">
generated content 1
// </cogeni>
`,
		},
		{
			name: "replacement with different attribute order",
			input: `
// <generated id="test1" by="cogeni">
old content
// </cogeni>
`,
			outputs:  outputs,
			cleanAll: false,
			expected: `
// <generated id="test1" by="cogeni">
generated content 1
// </cogeni>
`,
		},
		{
			name: "replacement with extra whitespace",
			input: `
// <generated   id = "test1"   by="cogeni" >
old content
// </cogeni>
`,
			outputs:  outputs,
			cleanAll: false,
			expected: `
// <generated   id = "test1"   by="cogeni" >
generated content 1
// </cogeni>
`,
		},
		{
			name: "clean mode with empty output",
			input: `
// <generated by="cogeni" id="test1">
old content
// </cogeni>
`,
			outputs:  map[string]string{"test1": ""},
			cleanAll: true,
			expected: `
// <generated by="cogeni" id="test1">
// </cogeni>
`,
		},
		{
			name: "clean mode with unknown block",
			input: `
// <generated by="cogeni" id="unknown">
old content
// </cogeni>
`,
			outputs:  outputs, // "unknown" is not here
			cleanAll: true,
			expected: `
// <generated by="cogeni" id="unknown">
// </cogeni>
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ReplaceGeneratedBlocks(tt.input, tt.outputs, tt.cleanAll)
			if got != tt.expected {
				t.Errorf("ReplaceGeneratedBlocks() = \n%q\n, want \n%q", got, tt.expected)
			}
		})
	}
}
