#!/bin/bash
set -e

DOCS_DIR="docs/docusaurus/docs/api"
MODULE=$(go list -m)

mkdir -p "$DOCS_DIR"

if ! command -v gomarkdoc &>/dev/null; then
	echo "gomarkdoc not found. Installing..."
	go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
fi

echo "Generating Go API docs with gomarkdoc..."

# Generate docs for all packages recursively
# We use --output to specify the output format/location
# gomarkdoc doesn't support -r recursive easily with flat output to directories,
# but we can list packages and loop.

# Create _category_.json for the API section
# Ensure slug matches docusaurus.config.ts configuration (/docs/api)
cat <<EOF >"$DOCS_DIR/_category_.json"
{
  "label": "Go API",
  "position": 9,
  "link": {
    "type": "generated-index",
    "slug": "api",
    "description": "Go API Reference for cogeni packages."
  }
}
EOF

# Function to generate doc for a package
generate_pkg_doc() {
	local pkg=$1
	local relpkg=${pkg#"$MODULE"/}
	if [ "$pkg" == "$MODULE" ]; then relpkg="root"; fi

	# Create directory structure for the package documentation
	local outpath="$DOCS_DIR/$relpkg.md"
	local outdir
	outdir=$(dirname "$outpath")
	mkdir -p "$outdir"
	echo "Generating $pkg -> $outpath"
	gomarkdoc --output "$outpath" "$pkg"

	# Fix generated internal links for Docusaurus
	# gomarkdoc generates links like `[Type](#Type)` but Docusaurus might
	# require lowercased anchors. In Docusaurus, headings are lowercased and spaces are replaced with dashes.
	# Let's perform a simple sed replacement if needed, or rely on Docusaurus resolving it.
	# The main issue with gomarkdoc and Docusaurus is often the `#type-` vs `#Type`
	# gomarkdoc typically uses exact case.

	# Fix heading anchors
	# In gomarkdoc, it links to `#type-MyType` or `#MyType`.
	# We can use a simple sed to make all anchor links lowercase to match Docusaurus's autogenerated IDs.
	# Example: `[Text](#Anchor)` -> `[Text](#anchor)`
	# We'll use perl to lower case the anchor part of internal links.
	# We also handle the `<#Anchor>` format often generated by gomarkdoc.
	perl -pi -e 's/\]\(<?#([A-Za-z0-9._-]+)>?\)/](#\L$1)/g' "$outpath"

	# Add custom heading IDs for Docusaurus by moving <a name="..."></a> into the heading
	# This is the most reliable way to handle anchors in Docusaurus.
	perl -i -0777 -pe 's/<a name="([^"]+)"><\/a>\s+(#+\s+[^\n]+)/$2 {#\L$1}/g' "$outpath"
}

# List all packages and generate docs
go list ./src/... | while read -r pkg; do
	generate_pkg_doc "$pkg"
done

echo "Go API docs generated successfully."
